[tool.poetry]
name = "linear-regression"
version = "0.1.0"
description = ""
authors = ["abdalrahmansamara <abdsamara_1998@yahoo.com>"]

[tool.poetry.dependencies]
python = "^3.9"
matplotlip = "^0.2"
pandas = "^1.2.4"
sklearn = "^0.0"
jupyterlab = "^3.0.16"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
